Repository planetarium/NineChronicles.Bridge, pull requests merged in 2023-11, with the labels that each got.

#7 Fix error against nullable fields on garage action
  src/headless-graphql-client.ts
Labels: Extra Small

#9 Fix spec file
  src/asset-transfer.ts
  src/headless-graphql-client.spec.ts
Labels: Extra Small

#10 🔨 PDX-76: Make `AssetDownstreamObserver` work
  src/asset-burner.ts
  src/headless-graphql-client.ts
  src/index.ts
  src/observers/asset-downstream-observer.ts
Labels: bug

#12 🔨 PDX-82: Check build in CI step
  .github/workflows/build.yaml
Labels: Extra Small, ci

#11 🐬 PDX-77: Push Docker image in GH-Actions
  .github/workflows/push_docker_image.yaml
Labels: Extra Small, ci

#14 Guarantee exclusive running in signer level
  package.json
  src/asset-burner.ts
  src/asset-transfer.ts
  src/headless-graphql-client.spec.ts
  src/index.ts
  src/minter.spec.ts
  src/minter.ts
  src/observers/garage-observer.spec.ts
  src/signer.ts
  yarn.lock
Labels: Medium

#19 🔨 PDX-116: Handle `transfer_asset[0-9]*` only
  src/headless-graphql-client.ts
Labels: Extra Small

#21 Forward garage memo to mint asset action
  src/interfaces/minter.ts
  src/minter.spec.ts
  src/minter.ts
  src/observers/asset-transferred-observer.ts
  src/observers/garage-observer.ts
Labels: Extra Small

#22 🔨 PDX-81: Check lint in CI step
  .github/workflows/build.yaml
  .vscode/extensions.json
  biome.json
  package.json
  src/asset-burner.ts
  src/asset-transfer.ts
  src/headless-graphql-client.spec.ts
  src/headless-graphql-client.ts
  src/index.ts
  src/interfaces/asset-transfer.ts
  src/interfaces/headless-graphql-client.ts
  src/interfaces/minter.ts
  src/interfaces/monitor-state-store.ts
  src/minter.spec.ts
  src/minter.ts
  src/monitors/assets-transferred-monitor.ts
  src/monitors/garage-unload-monitor.ts
  src/monitors/index.ts
  src/monitors/ninechronicles-block-monitor.ts
  src/monitors/triggerable-monitor.ts
  src/observers/asset-downstream-observer.ts
  src/observers/asset-transferred-observer.ts
  src/observers/garage-observer.spec.ts
  src/observers/garage-observer.ts
  src/signer.ts
  src/sqlite3-monitor-state-store.ts
  src/types/asset-transferred-event.ts
  src/types/fungible-item-id.ts
  src/types/garage-unload-event.ts
  yarn.lock
Labels: Extra Large

#27 👯 PDX-123: Support gracefully shutdown
  src/index.ts
  src/monitors/assets-transferred-monitor.ts
  src/monitors/garage-unload-monitor.ts
  src/monitors/ninechronicles-block-monitor.ts
  src/monitors/triggerable-monitor.ts
  src/shutdown-handler.ts
  src/types/shutdown-checker.ts
Labels: Extra Small

#28 🚤 PDX-128: Decrease `AUTHORIZED_BLOCK_INTERVAL` to 1
  src/monitors/ninechronicles-block-monitor.ts
Labels: Extra Small

#29 🔨 PDX-122: Check `transactionResult.txStatus` is `SUCCESS`
  src/headless-graphql-client.ts
  src/interfaces/headless-graphql-client.ts
  src/monitors/assets-transferred-monitor.ts
  src/monitors/garage-unload-monitor.ts
  src/types/transaction-result.ts
Labels: bug, Extra Small

#33 🔨 PDX-80: Load and store latest block by monitors
  src/headless-graphql-client.spec.ts
  src/index.ts
  src/interfaces/monitor-state-handler.ts
  src/interfaces/monitor-state-store.ts
  src/monitor-state-handler.ts
  src/monitors/assets-transferred-monitor.ts
  src/monitors/garage-unload-monitor.ts
  src/monitors/ninechronicles-block-monitor.ts
  src/monitors/triggerable-monitor.ts
  src/observers/asset-transferred-observer.ts
  src/observers/garage-observer.spec.ts
  src/observers/garage-observer.ts
  src/sqlite3-monitor-state-store.ts
Labels: bug, Medium

#34 🧹 PDX-129: Remove `TriggerableMonitor`
  src/monitors/ninechronicles-block-monitor.ts
  src/monitors/triggerable-monitor.ts
Labels: Medium

#32 axios -> urql, retry handling, externalize query and typing results with codegen.
  .gitignore
  .yarn/install-state.gz
  .yarnrc.yml
  biome.json
  codegen.ts
  package.json
  schema.graphql
  src/graphql/GetAssetTransferred.graphql
  src/graphql/GetBlockHash.graphql
  src/graphql/GetBlockIndex.graphql
  src/graphql/GetGarageUnloads.graphql
  src/graphql/GetGenesisHash.graphql
  src/graphql/GetNextTxNonce.graphql
  src/graphql/GetTipIndex.graphql
  src/graphql/GetTransactionResult.graphql
  src/graphql/StageTransaction.graphql
  src/headless-graphql-client.ts
  src/interfaces/headless-graphql-client.ts
  src/types/garage-unload-event.ts
  tsconfig.json
  yarn.lock
Labels: enhancement, Extra Large

#46 🕐 PDX-152: Create tx with super future datetime
  src/signer.ts
Labels: bug

#41 Record Staged Transaction
  package.json
  prisma/schema.prisma
  src/asset-burner.ts
  src/asset-transfer.ts
  src/graphql/GetAssetTransferred.graphql
  src/graphql/GetGarageUnloads.graphql
  src/headless-graphql-client.spec.ts
  src/headless-graphql-client.ts
  src/index.ts
  src/interfaces/asset-burner.ts
  src/interfaces/asset-transfer.ts
  src/interfaces/headless-graphql-client.ts
  src/interfaces/job-execution-store.ts
  src/interfaces/minter.ts
  src/job-execution-store.ts
  src/minter.ts
  src/monitors/assets-transferred-monitor.ts
  src/monitors/garage-unload-monitor.ts
  src/monitors/index.ts
  src/monitors/ninechronicles-block-monitor.ts
  src/observers/asset-downstream-observer.ts
  src/observers/asset-transferred-observer.ts
  src/observers/garage-observer.spec.ts
  src/observers/garage-observer.ts
  src/signer.ts
  src/types/asset-transferred-event.ts
  src/types/garage-unload-event.ts
  src/types/transaction-location.ts
Labels: enhancement, Large

#49 Make `index.js` PID 1
  Dockerfile
Labels: bug, Extra Small

#50 More slack notify
  src/asset-burner.ts
  src/asset-transfer.ts
  src/graphql/GetAssetTransferred.graphql
  src/graphql/GetGarageUnloads.graphql
  src/headless-graphql-client.spec.ts
  src/headless-graphql-client.ts
  src/index.ts
  src/interfaces/asset-burner.ts
  src/interfaces/asset-transfer.ts
  src/interfaces/headless-graphql-client.ts
  src/interfaces/minter.ts
  src/minter.ts
  src/monitors/assets-transferred-monitor.ts
  src/monitors/garage-unload-monitor.ts
  src/monitors/index.ts
  src/monitors/ninechronicles-block-monitor.ts
  src/observers/asset-downstream-observer.ts
  src/observers/asset-transferred-observer.ts
  src/observers/garage-observer.spec.ts
  src/observers/garage-observer.ts
  src/signer.ts
  src/slack/messages/bridge-event.ts
  src/slack/messages/utils.ts
  src/types/asset-transferred-event.ts
  src/types/garage-unload-event.ts
  src/types/transaction-location.ts
Labels: enhancement, Large

#51 Dont use timestamp
  src/graphql/GetAssetTransferred.graphql
  src/graphql/GetGarageUnloads.graphql
  src/headless-graphql-client.ts
  src/observers/garage-observer.spec.ts
  src/types/asset-transferred-event.ts
  src/types/garage-unload-event.ts
Labels: bug, Extra Small

#52 Fix BridgeEvent src-dst noshow bug
  src/slack/messages/bridge-event.ts
Labels: bug, Extra Small

#53 ignore checksum
  src/observers/asset-downstream-observer.ts
Labels: bug, Extra Small

#55 Rename AppErrorEvent -> BridgeErrorEvent
  src/observers/asset-downstream-observer.ts
  src/observers/asset-transferred-observer.ts
  src/observers/garage-observer.ts
  src/slack/messages/bridge-error-event.ts
Labels: bug

#56 🔨 PDX-169: Introduce ITxPool
  src/headless-graphql-client.spec.ts
  src/index.ts
  src/interfaces/txpool.ts
  src/minter.spec.ts
  src/monitors/ninechronicles-block-monitor.ts
  src/observers/garage-observer.spec.ts
  src/signer.ts
  src/txpool/headless.ts
  src/txpool/index.ts
  src/txpool/local.ts
  src/utils/delay.ts
  src/utils/tx.ts
Labels: bug, Large

#57 Correct import path
  src/interfaces/txpool.ts
  src/txpool/headless.ts
  src/txpool/local.ts
  src/types/signed-tx.ts
Labels: bug, Extra Small

#59 Drop txs in journal by ascending nonces
  src/txpool/local.ts
Labels: bug, Extra Small

#58 Make URQL never drop a request.
  src/headless-graphql-client.spec.ts
  src/headless-graphql-client.ts
  src/index.ts
  src/minter.spec.ts
  src/observers/garage-observer.spec.ts
Labels: enhancement, Small

#61 Implement transactional bridge processor
  .env.sample
  package.json
  prisma/migrations/20231127180402_initialize/migration.sql
  prisma/migrations/20231128024918_block_redesign/migration.sql
  prisma/migrations/20231128082140_response_type/migration.sql
  prisma/migrations/20231128090826_remove_network_genesishash/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  src/asset-burner.ts
  src/asset-transfer.ts
  src/headless-graphql-client.spec.ts
  src/index.ts
  src/minter.ts
  src/monitors/assets-transferred-monitor.ts
  src/monitors/garage-unload-monitor.ts
  src/observers/garage-observer.spec.ts
  src/observers/garage-observer.ts
  src/signer.ts
  src/sync/downstream/events/transfer.ts
  src/sync/downstream/index.ts
  src/sync/processor.ts
  src/sync/stage.ts
  src/sync/txresult.ts
  src/sync/types.ts
  src/sync/upstream/events/garage.ts
  src/sync/upstream/events/transfer.ts
  src/sync/upstream/index.ts
  src/sync/utils.ts
  src/tx.ts
  yarn.lock
Labels: Extra Large

#62 🔨 PDX-185: Correct unload-garage event handling
  src/headless-graphql-client.spec.ts
  src/headless-graphql-client.ts
  src/index.ts
  src/observers/garage-observer.spec.ts
  src/observers/garage-observer.ts
Labels: bug, Small

#63 Include prisma migrations to Docker image
  Dockerfile
Labels: Extra Small
